name: az-env
channels:
- anaconda
- conda-forge
- defaults
dependencies:
- python>=3.7
- jupyter_contrib_nbextensions
- pip
- pandas
- pip:
  - azureml-sdk
  - azureml-sdk[explain,automl]
  - azureml-widgets